image : openjdk:8

variables:
  DOCKER_HOST: tcp://localhost:2375

services:
 - nexus.informatik.haw-hamburg.de/docker:stable-dind

stages:
  - build

build:
  stage: build
  tags:
    - k8s
  only:
    - master
  script:
    - ./gradlew build
